// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using softline.db.Context;

namespace softline.db.Migrations
{
    [DbContext(typeof(ObjectivesContext))]
    partial class ObjectivesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("softline.db.Model.Objective", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(75)");

                    b.Property<int>("status_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Objectives");
                });

            modelBuilder.Entity("softline.db.Model.Status", b =>
                {
                    b.Property<int>("status_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("status_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(75)");

                    b.HasKey("status_id");

                    b.ToTable("Statuses");
                });
#pragma warning restore 612, 618
        }
    }
}
